// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"first-project/app"
	"first-project/db/connection"
	"first-project/helper"
	"first-project/pkg/bicycle/bicycle.controller"
	"first-project/pkg/bicycle/bicycle.repository"
	"first-project/pkg/bicycle/bicycle.service"
	"first-project/pkg/order/order.repository"
	"first-project/pkg/order/order.service"
	"first-project/pkg/user/user.controller"
	"first-project/pkg/user/user.repository"
	"first-project/pkg/user/user.service"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
)

// Injectors from injector.go:

func StartServer() *echo.Echo {
	db := connection.DBConn()
	userRepo := userrepository.NewUserRepo(db)
	tokenUseCaseImpl := helper.NewTokenUseCase()
	userService := userservice.NewUserService(userRepo, tokenUseCaseImpl)
	userController := usercontroller.NewUserController(userService)
	bicycleRepo := bicyclerepository.NewBicycleRepo(db)
	bicycleService := bicycleservice.NewBicycleService(bicycleRepo)
	orderRepo := orderrepository.NewOrderRepo(db)
	orderService := orderservice.NewOrderService(orderRepo, tokenUseCaseImpl, bicycleRepo)
	bicycleController := bicyclecontroller.NewBicycleController(bicycleService, orderService)
	echoEcho := app.InitialServer(userController, bicycleController)
	return echoEcho
}

// injector.go:

var userSet = wire.NewSet(userrepository.NewUserRepo, wire.Bind(new(userrepository.UserRepoInterface), new(*userrepository.UserRepo)), helper.NewTokenUseCase, wire.Bind(new(helper.TokenUseCaseInterface), new(*helper.TokenUseCaseImpl)), userservice.NewUserService, wire.Bind(new(userservice.UserServiceInterface), new(*userservice.UserService)), usercontroller.NewUserController, wire.Bind(new(usercontroller.UserControllerInterface), new(*usercontroller.UserController)))

var orderSet = wire.NewSet(orderrepository.NewOrderRepo, wire.Bind(new(orderrepository.OrderRepositoryInterface), new(*orderrepository.OrderRepo)), orderservice.NewOrderService, wire.Bind(new(orderservice.OrderServiceInterface), new(*orderservice.OrderService)))

var bicycleSet = wire.NewSet(bicyclerepository.NewBicycleRepo, wire.Bind(new(bicyclerepository.BicycleRepositoryInterface), new(*bicyclerepository.BicycleRepo)), bicycleservice.NewBicycleService, wire.Bind(new(bicycleservice.BicycleServiceInterface), new(*bicycleservice.BicycleService)), bicyclecontroller.NewBicycleController, wire.Bind(new(bicyclecontroller.BicycleControllerInterface), new(*bicyclecontroller.BicycleController)))
